### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a link to get your app via the [IzzyOnDroid open source app repo](https://apt.izzysoft.de/fdroid/) in a F-Droid client.

It will help people without Google Play to find and use your app, as well as helping them to keep it updated.

Since the apk provided by IzzyOnDroid is simply taken from the Release Section of this repo, please never forget to attach your signed apk to the release when tagging a new version, so that Izzy can take it and make it available via a F-Droid client to your users !

### CODE REVIEW

**Comment by zimbelstern** [comment]
Hi,
thank you for your PR. Before merging, I need to git some things right with the Tournant repository because there seem to be different non-compatible versions here and on weblate. I am not really a git expert (yet).
I appreciate Tournant being a part of IzzyOnDroid's repository. Where does it get the metadata from? I haven't any in the repository yet. I am going to setting up fastlane later.
BTW: Since Tournant is FOSS, I would love to get it into the main F-Droid repo as well. But I didn't manage to make a reproducible build with the F-Droid server last year and setting up an own repository was way easier.

**Comment by Poussinou** [comment]
Hey @IzzySoft !

Sorry to ping you, you can probably answer the question better than me ;)

**Comment by IzzySoft** [comment]
> Where does it get the metadata from? I haven't any in the repository yet. I am going to setting up fastlane later.

Usually from Fastlane if available, otherwise created based on information in the repo (or from its PlayStore listing if available there). And I gladly provide what I've set up: it's already in Fastlane format, so you could integrate it as-is (and then update as you see fit).

> I would love to get it into the main F-Droid repo as well.

You're welcome!

> But I didn't manage to make a reproducible build with the F-Droid server last year

A week ago I wouldn't have thought I'd manage that either. Got a bit easier it seems: I've just pushed in 5 RBs this week. The first one was hard and I needed much help from my friends. Got easier then as I'd been making notes :rofl:

Apart from that: RB is highly recommended, but not mandatory.

**Comment by IzzySoft** [comment]
PS: You can also [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app in my repo if you wish :wink:

**Comment by zimbelstern** [comment]
> Usually from Fastlane if available, otherwise created based on information in the repo (or from its PlayStore listing if available there). And I gladly provide what I've set up: it's already in Fastlane format, so you could integrate it as-is (and then update as you see fit).

Thanks; what do you mean by that? I have the metadata (changelog, description, etc.) already in a fastlane-like structure and just need to move it over from my local fdroidserver into the Tournant repository. But I haven't set any lane up. I need to get more familiar with gradle and fastlane because I want a lane which copies the apk, does fdroid update and deploy and creates a release on Github. Have you got such a thing?

> Apart from that: RB is highly recommended, but not mandatory.

I know. When I was trying last year, I found that most of all apps I had installed were signed by F-Droid. I do not want this as it prevents users to upgrade with an "officially signed" app or vice versa. I will try again later.

**Comment by IzzySoft** [comment]
I just have set up the **metadata** in [fastlane structure](https://gitlab.com/-/snippets/1895688) (so no fastlane binaries) here locally. And no, fdroid doesn't create releases at Github – but my updater **pulls** them **from** Github to place them into my local repository – which then gets synced once the index was rebuilt.

And while last year your two hands would have been enough to count the number of apps using RB – today it wouldn't even help to take your shoes off. You'd need an entire soccer team to do that (bring their hands and take their shoes off for counting). Last week alone, 5 new RB apps have been added.

**Comment by zimbelstern** [comment]
I added your badge and created one for my own repo. ;-)
Next step: Adding Fastlane metadata and trying an F-Droid reproducible build.

**Comment by IzzySoft** [comment]
Let me know when a) you want the fastlane structures from my repo and/or b) yours are set up so I can tell my updater to pull them along :star_struck:

**Comment by zimbelstern** [comment]
b) ;-)

**Comment by zimbelstern** [comment]
Hey @IzzySoft, I've added some screenshots and hope your updater will pull updates like these automatically!

By the way, I've worked hard to get Tournant into F-Droid's main repo and [opened an merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12550) two weeks ago. But don't really know what happens next and how long the review will take.

**Comment by IzzySoft** [comment]
> I've added some screenshots and hope your updater will pull updates like these automatically!

Not before I'm telling it to look there – on it now!

Meanwhile, could you please fix the link the badge points to so it leads directly to your app? `https://apt.izzysoft.de/fdroid/index/apk/eu.zimbelstern.tournant` or `https://apt.izzysoft.de/packages/eu.zimbelstern.tournant/` should both work for that.

May I suggest an enhancement to your `full_description.txt` to help interested folks to find the *Gourmand Recipe Manager* – by making the name a clickable link? That's what I currently have in on my end and would like to keep up:

`<a href='https://github.com/GourmandRecipeManager/gourmand'>Gourmand/Gourmet Recipe Manager</a>`

OK, enabled everything else now and triggered an update, Fastlane is just being pulled now (and also found an updated `FUNDING.yml` which was pulled along). Should become visible with the next sync then.

**Comment by zimbelstern** [comment]
Since Tournant is merged into F-Droid's main repo now (yay!), the question is if it will stay in your repo at all or if you prefer to withdraw it?

**Comment by IzzySoft** [comment]
I usually remove apps after a decent overlap then – unless explicitly asked to keep them. So especially small apps with reproducible builds enabled at F-Droid (Tournant meets both) are welcome to stay. Your choice then: Stay?

And btw: that `<a href` is supported by F-Droid as well if that was part of the question :wink:

**Comment by zimbelstern** [comment]
I know that I can add the href. Just wanted to make sure that I don't tweak a badge with a deprecation date next week. I could replace it with the F-Droid badge instead.

I like the concept of decentralisation. And I appreciate your work and have used your repo for years myself. But in this case, I think you can abandon Tournant. It wouldn't make an awful lot of difference regarding the publicity, would it? And I am eager to keep it in F-Droid's main repo and have an eye on the reproducibility of the build. Whoever does not like the main sources can install it from my own repo.

Of course I'm not opposed if you want to keep it. But for my part, free up the space as soon as it is available from F-Droid's servers.

**Comment by IzzySoft** [comment]
As you wish. Thanks to reproducible builds, folks can install from F-Droid and then profit from faster updates via my repo should they choose to – so I offer the option ***if you want it.*** I do not insist of course – and should you want it back one day, it's also easily restored if we remove it "now". So I'm fine both ways :wink:

**Comment by IzzySoft** [comment]
Congrats! Tournant just showed up in the index of F-Droid.org. Final last words? :smile: Your app is quite decently sized, even 3 versions of it currently would take not even a quarter of the space a single version of some other apps eats (oops).

**Comment by zimbelstern** [comment]
Thanks! Of course, I was keeping track of the last build cycle. ;-) Crazy you did, too – given the many many apps you observe everyday.

Well, as you may have noticed, Tournant is mainly just an XML parser with only a few extra functions and small resources which keeps the size down. I have many other ideas for Tournant in mind, regarding sync, editing, tools, etc. – some of which would expand the scope beyond users of Gourmand.

However, since I am not a professionally trained IT developer and still learning (which probably applies to many other foss devs), some things require a lot of time and focus and sometimes I have to stop myself from spending too much on this unpaid project.

I am very happy that Tournant has eventually been uploaded on f-droid.org and I am satisfied with the usability of the app for now. I expect version 1.1.8 (or 1.2.* or 2.*) to be at least a few months away. ;-)

Bye for now Izzy, until my next app (just kidding).

**Comment by zimbelstern** [comment]
PS: New readme with replaced badge is in progress. ;)

**Comment by IzzySoft** [comment]
> Crazy you did, too – given the many many apps you observe everyday.

I have to – I'm the one announcing new arrivals. But I didn't follow it that closely in the build queue – it was rather the "watchdog" announcing the new index and what it brought :wink: There's Brainstorm on IRC/Matrix, and my own watchdog reporting to my mail. I then post the [#AndroidAppRain](https://floss.social/tags/AndroidAppRain) :smiley:

> I am very happy that Tournant has eventually been uploaded on f-droid.org and I am satisfied with the usability of the app for now. I expect version 1.1.8 (or 1.2.* or 2.*) to be at least a few months away. ;-)

Yupp, I'm happy along with you. And I understand you see no reason for "faster updates". And as you just announced *replacing* badges, I'll follow suite and remove the app from my repo after the mentioned overlap. Should you want it back one day, just "ring ma bell" and I'll swiftly add it back.

All the best then for you and all your projects, current and future ones!

**Pull request closed without merging**
