### PR TITLE
add-tr-locales

### PR DESCRIPTION
**Pull request by mikropsoft**
As far as I see on weblate, language cannot be added.

### CODE REVIEW

**Comment by Zimbelstern** [comment]
> As far as I see on weblate, language cannot be added.

Thank you for your contribution. :) It should be possible to add another language on the Weblate instance. Maybe you have to log in.

**Comment by mikropsoft** [comment]
> > As far as I see on weblate, language cannot be added.
> 
> Thank you for your contribution. :) It should be possible to add another language on the Weblate instance. Maybe you have to log in.

Although I can add languages, I cannot upload language files

**Comment by Zimbelstern** [comment]
I doubt that this is possible. But I can merge your PR when you remove the non-translable string from the translation file.

**Review by Zimbelstern — CHANGES_REQUESTED** [review]

**Comment by mikropsoft** [comment]
Done, thanks.

**Pull request merged**
